version: '{build}'

environment:
    matrix:
        - PYTHON: "C:\\Python35"
        - PYTHON: "C:\\Python35-x64"
        - PYTHON: "C:\\Python36"
        - PYTHON: "C:\\Python36-x64"

install:
    - '%PYTHON%\\python.exe -m pip install -U pip'
    - '%PYTHON%\\python.exe -m pip install -r requirements-dev.txt'

build: off

test_script:
    - '%PYTHON%\\python.exe -m tox -e check,py'
